dist: xenial
sudo: required
language: python
python:
  - 3.5
  - 3.6
before_install:
- sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get -y update
- sudo apt-get install -y libgdal-dev build-essential libproj-dev
- if [ $RASTERIO_VERSION == "latest" ]; then pip install rasterio --no-binary :all:; else pip install rasterio==$RASTERIO_VERSION --no-binary :all:; fi;
install:
- pip install -r requirements.txt
- pip install pytest coveralls
- pip install .
script:
- coverage run --source=tilematrix setup.py test
after_success:
- coveralls
env:
  matrix:
    - RASTERIO_VERSION="1.0.21"
    - RASTERIO_VERSION="latest"
