dist: trusty
sudo: required
language: python
python:
- '3.5'
- '3.6'
- '3.7'
  dist: xenial
  sudo: true
before_install:
- sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get -y update
- sudo apt-get install -y libgdal-dev build-essential libproj-dev
- "pip install --no-binary :all: rasterio==1.0.21"
install:
- pip install -r requirements.txt
- pip install pytest coveralls
- pip install .
script:
- coverage run --source=tilematrix setup.py test
after_success:
- coveralls
