dist: trusty
sudo: required
language: python
python:
- '2.7'
virtualenv:
  system_site_packages: true
before_install:
- sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get -y update
- sudo apt-get install -y libgdal-dev build-essential gdal-bin
install:
- pip install gdal==2.1.3 --global-option=build_ext --global-option="-I/usr/include/gdal/"
- pip install -r requirements.txt
- pip install pytest coveralls
- pip install .
script:
- coverage run --source=tilematrix setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: ungarj
  password:
    secure: B2K0tDNUCnKAVFrOGPWqnRoxhh4xx/7YOFDFnT8Rz93vMjW9CJIK/3xfP1EYTNP8Y6R5T2aA2MIMRp/D24vJxgcaqQlqM2qY1rNu5ANuBW5I+ebt+nb56FX4dHHU7UE3FzoVhgr67gxO9uzF6oER/FjN9goH5jhLAbfndCAQqRDe3n9ntCe7i8/WZ+OS5e0CBwqhMMd3PxyN1s9Sn1Bu1ZzLc7Q5MkC0BwdAa7mnr0a+qoxOQKCy/pMiVOOv6Y6Pt8Yah0j0Vbm4UfU4lfAHrhtii2J28hWijOhsiwVWOi7X2yiIK7wLv1uQrNR2bFTv4O2RQEf2rHxZjU7LeVCKciBEuCcAEUJzhZkBJXhco9ERPGhO8VCOuMhE3rN4NCmJImx8s0jm+MEHmdd+fa1uGHKW26Z4ceRyEYNvPTu37XaF9yRTL7THHDbHehvg8oytMr07ZZJdB1mz8UkW2jo4hyVwFYly9FsMOrKu7zKurrE+x9JU/cRia57w3GaZPRbq0som3osB/veX8NIXa/LPCoxDagQd3UYXRu+y9U/vGsSifKI7dWLEZsGwGBrfOzmEd9b4ocq0F2dPy2ZbDKSfn4zqPIx5JC1lFf+wIOXJNSOA7datQhBUhyzO22X4dWjejzN4ASso1fCXuQVIIgEd52kFOV39GciD+WarkB+Exeg=
  on:
    tags: true
    branch: master
