name: conda-build-publish-env
channels:
  - conda-forge
dependencies:
  - anaconda-client
  - conda-build
  - gdal 
  - rasterio>=1.0.21
  - pytest-runner
  - pytest
  - pip
  - conda:
    - -f ./requirements.txt 