name: conda-build-publish-env
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - conda-build
  - conda-verify
  - pytest-runner
  - pytest
  - gdal
  - numcodecs
  - pip
  - pip:
    - -r ../requirements.txt --no-binary :all:
