name: conda-build-publish-env
channels:
  - conda-forge
  - defaults
  - .conda/
dependencies:
  - affine
  - anaconda-client
  - click>=7.1.1
  - conda-build
  - conda-verify
  - gdal
  - geojson
  - rasterio>=1.0.21
  - shapely  
  - pytest-runner
  - pytest
