name: conda-build-publish-env
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - conda-build
  - pytest-runner
  - pytest
  - gdal>=3.5.2
  - pip
  - pip:
    - -r ../requirements.txt
