{% set name = "tilematrix" %}
{% set version = "2022.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ungarj/tilematrix
  git_rev: {{ version }}

build:
  entry_points:
    - tmx=tilematrix.tmx.main:tmx
  noarch: python
  script: python setup.py install
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - affine
    - click
    - geojson
    - rasterio >=1.0.21
    - shapely

test:
  commands:
    - tmx --help
    - pytest test/* -v
  source_files:
    - test/*
  requires:
    - pytest
    - pytest-runner

about:
  home: https://github.com/ungarj/tilematrix
  summary: helps handling tile pyramids
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ungarj
    - Scartography
