{% set name = "tilematrix" %}
{% set version = "2022.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: pip install -e . --no-deps
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - affine
    - click
    - geojson
    - rasterio >=1.0.21
    - shapely

about:
  home: https://github.com/ungarj/tilematrix
  summary: helps handling tile pyramids
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ungarj
    - Scartography
