name: Build, Test and Upload Conda Package

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2          
    - uses: conda-incubator/setup-miniconda@v2
      with: 
        auto-activate-base: false
        python-version: 3.9
        activate-environment: conda-build-publish-env
        auto-update-conda: true
        environment-file: .conda/conda-environment.yaml  
    - name: build conda package
      run: conda index && conda-build --output-folder .conda/ --no-anaconda-upload tilematrix .conda/
    # - name: upload conda package
    # run: export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }} && anaconda upload --force .conda/noarch/*.tar.bz2
