name: Build and Test Conda Package

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2          
    - uses: conda-incubator/setup-miniconda@v2
      with: 
        auto-activate-base: false
        python-version: 3.9
        activate-environment: conda-build-publish-env
        auto-update-conda: true
        environment-file: .conda/conda-environment.yaml  
    - name: build and test conda package
      run: PKG_NAME=tilematrix && VERSION=$(python setup.py --version) && conda index && conda-build --no-anaconda-upload --verify $PKG_NAME .conda/meta.yaml && conda index && conda install -y --offline --use-local $PKG_NAME=$VERSION