name: Build, Test and Upload Conda Package

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with: 
        auto-activaye-base: true
        activate-environment: ""
    - uses: actions/checkout@v2        
    - name: build conda package
      run: conda install -y conda-build && conda index && conda-build --output-folder .conda/ --no-test --no-anaconda-upload tilematrix .conda/
    - name: install local conda build and test conda package
      run: conda install -c conda-forge -y gdal rasterio pytest-runner pytest && conda install -y --use-local tilematrix && pytest ./test/* -v
    # - name: upload conda package
    # run: conda install -y anaconda-client && export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }} && anaconda upload --force .conda/noarch/*.tar.bz2
