name: Build, Test and Upload Conda Package

on: [push]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2          
    - uses: conda-incubator/setup-miniconda@v2
      with: 
        auto-activate-base: false
        python-version: 3.9
        activate-environment: conda-build-publish-env
        auto-update-conda: true
        environment-file: .conda/conda-environment.yaml  
    - name: build conda package
      run: VERSION=$(python setup.py --version) && conda index && conda-build --no-anaconda-upload --verify tilematrix .conda/meta.yaml && conda index && conda install -y --offline --use-local tilematrix=$VERSION
    - name: upload conda package
      run: VERSION=$(python setup.py && export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }} && anaconda upload --force tilematrix=$VERSION
